### ISSUE TITLE
Delete an item by ID

### ISSUE THREAD

**Issue by freakeinstein** [Aquila-Network/AquilaDB#25]

**Comment by marijnl** [comment]
I supply the _id before adding it to the db

```
def convertDocuments(_id, vector):
{
            "vector": {
                "e": vector
            },
            "_id" : _id.encode('utf-8')
}
```

This way its easy to delete vectors using a deleteRequest without having to keep track over db keys

I noticed though that the vectors are only labeled as being deleted. They are not physically removed from disk

**Comment by freakeinstein** [comment]
@marijnl You are right. To remove a document from the database, what you need to do is set `_deleted` key to true, because AquilaDB follows Couch protocol and use PouchDB internally. But this doesn't remove that item from vector index. We need to do that as well. So, essentially, the implementation would be, we would delete the document the same way you have mentioned, which will trigger an internal change event which should call delete method on vector index. We appreciate your interest and are open to pull requests if you are able to pull this off..

**Comment by marijnl** [comment]
@freakeinstein I think i dont have permissions to create a branch and PR. Can you grant me access? I didnt fix this specific issue but a typing issue of env variables.

**Comment by freakeinstein** [comment]
@marijnl her are the steps to submit a pull request, which doesn't require write permissions.
1. Fork (will take a photocopy) this project as your personal repository
2. Clone that copy to your local system
3. Make changes to the source code
4. commit and push changes from your local system to your fork
5. create a pull request to a-mma AquilaDB
that's it!

**Comment by freakeinstein** [comment]
Code is rewritten. Bug is irrelevant and covered. closed.
