### ISSUE TITLE
[BUG] Kubernetes deploy command fails

### ISSUE THREAD

**Issue by dkawashima** [Aquila-Network/AquilaDB#66]
**Describe the bug**
error: error parsing https://github.com/a-mma/AquilaDB/blob/develop/kubernetes/aquiladb.yml: error converting YAML to JSON: yaml: line 115: mapping values are not allowed in this context

**To Reproduce**
Run this command: kubectl apply -f https://github.com/a-mma/AquilaDB/blob/develop/kubernetes/aquiladb.yml

**Expected behavior**
Successful launch of aquiladb as kubernetes service

**Server Logs**
If possible, collect logs from AquilaDB container by following below steps in your terminal:

1. run `docker ps` and note down container id for AquilaDB
2. run `docker exec -i -t <container id> /bin/bash`
3. run `pm2 logs` and copy contents from there

**please complete the following information:**
 - Host OS: [e.g. Ubuntu 18.04]
 - Docker image label (tag) [e.g. latest, bleeding, release-v0.2.2]
 - AquilaDB Version [e.g. v0.2.2]

**Additional context**

**Comment by JESWINKNINAN** [comment]
@dkawashima Please use the URL: https://raw.githubusercontent.com/a-mma/AquilaDB/develop/kubernetes/aquiladb.yml for the deployment. We will correct the URL in the documents

**Comment by dkawashima** [comment]
Thanks!

**Comment by dkawashima** [comment]
Also, still running into this error with the updated config. New to Kubernetes so bear with me. Tried to deploy AquilaDB in Kubernetes and getting this error:

```  MountVolume.SetUp failed for volume "aquiladb-volume" : hostPath type check failed: /var/lib/aquiladb is not a directory
```
How does one create this directory in a Kubernetes contianer/set this up? Thanks

**Comment by freakeinstein** [comment]
Kubernetes configs are no longer maintained. ADB architecture & specs changed. Closing.
