### ISSUE TITLE
Readme and wiki links broken by project migration from `a-mma/AquilaDB`

### ISSUE THREAD

**Issue by jdr-vintra** [Aquila-Network/AquilaDB#86]
Links on the readme and wiki still refer to the old project address and and so are broken.

**Comment by admin-adb** [comment]
Hi @jdr-vintra, thanks for reporting this issue. The wiki page is not relevant anymore and is taken down also removed invalid links from README as well. For documentation, visit https://docs.aquila.network (contains most information and is still undergoing content improvement).
