### ISSUE TITLE
Wikipedia Dump

### ISSUE THREAD

**Issue by MikeyBeez** [Aquila-Network/AquilaDB#91]
I'm interested in putting Wikipedia onto your database.  Do you have a public forum where I can get advice for this?  I assume someone has done this already.  Thanks for making a great program!   Sorry for putting this into issues.

**Comment by freakeinstein** [comment]
Hi @MikeyBeez , that's very interesting. I'm unaware of anybody who put the entire Wikipedia dump into AquilaDB. Our benchmarks didn't exceed 1 million sentences of average length per DB. That said, I'm happy to help you in any way possible. Generally, we use this [Discord server](https://discord.com/invite/5YP7zHS) for casual discussions/dev support. If you don't mind, let's meet there.
